/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as EntrepreneursRouteImport } from './routes/entrepreneurs'
import { Route as JuniorRouteImport } from './routes/junior'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as YoungRouteImport } from './routes/young'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrepreneursRoute = EntrepreneursRouteImport.update({
  id: '/entrepreneurs',
  path: '/entrepreneurs',
  getParentRoute: () => rootRouteImport,
} as any)
const JuniorRoute = JuniorRouteImport.update({
  id: '/junior',
  path: '/junior',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const YoungRoute = YoungRouteImport.update({
  id: '/young',
  path: '/young',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/entrepreneurs': typeof EntrepreneursRoute
  '/junior': typeof JuniorRoute
  '/programs': typeof ProgramsRoute
  '/young': typeof YoungRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/entrepreneurs': typeof EntrepreneursRoute
  '/junior': typeof JuniorRoute
  '/programs': typeof ProgramsRoute
  '/young': typeof YoungRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/entrepreneurs': typeof EntrepreneursRoute
  '/junior': typeof JuniorRoute
  '/programs': typeof ProgramsRoute
  '/young': typeof YoungRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/entrepreneurs' | '/junior' | '/programs' | '/young'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/entrepreneurs' | '/junior' | '/programs' | '/young'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/entrepreneurs'
    | '/junior'
    | '/programs'
    | '/young'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EntrepreneursRoute: typeof EntrepreneursRoute
  JuniorRoute: typeof JuniorRoute
  ProgramsRoute: typeof ProgramsRoute
  YoungRoute: typeof YoungRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrepreneurs': {
      id: '/entrepreneurs'
      path: '/entrepreneurs'
      fullPath: '/entrepreneurs'
      preLoaderRoute: typeof EntrepreneursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/junior': {
      id: '/junior'
      path: '/junior'
      fullPath: '/junior'
      preLoaderRoute: typeof JuniorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/young': {
      id: '/young'
      path: '/young'
      fullPath: '/young'
      preLoaderRoute: typeof YoungRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EntrepreneursRoute: EntrepreneursRoute,
  JuniorRoute: JuniorRoute,
  ProgramsRoute: ProgramsRoute,
  YoungRoute: YoungRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
