/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EntrepreneursRouteImport } from './routes/entrepreneurs'
import { Route as JoinRouteImport } from './routes/join'
import { Route as JuniorRouteImport } from './routes/junior'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as YoungRouteImport } from './routes/young'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrepreneursRoute = EntrepreneursRouteImport.update({
  id: '/entrepreneurs',
  path: '/entrepreneurs',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const JuniorRoute = JuniorRouteImport.update({
  id: '/junior',
  path: '/junior',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const YoungRoute = YoungRouteImport.update({
  id: '/young',
  path: '/young',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/entrepreneurs': typeof EntrepreneursRoute
  '/join': typeof JoinRoute
  '/junior': typeof JuniorRoute
  '/programs': typeof ProgramsRoute
  '/young': typeof YoungRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/entrepreneurs': typeof EntrepreneursRoute
  '/join': typeof JoinRoute
  '/junior': typeof JuniorRoute
  '/programs': typeof ProgramsRoute
  '/young': typeof YoungRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/entrepreneurs': typeof EntrepreneursRoute
  '/join': typeof JoinRoute
  '/junior': typeof JuniorRoute
  '/programs': typeof ProgramsRoute
  '/young': typeof YoungRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/classes'
    | '/contact'
    | '/dashboard'
    | '/entrepreneurs'
    | '/join'
    | '/junior'
    | '/programs'
    | '/young'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/classes'
    | '/contact'
    | '/dashboard'
    | '/entrepreneurs'
    | '/join'
    | '/junior'
    | '/programs'
    | '/young'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/classes'
    | '/contact'
    | '/dashboard'
    | '/entrepreneurs'
    | '/join'
    | '/junior'
    | '/programs'
    | '/young'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ClassesRoute: typeof ClassesRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EntrepreneursRoute: typeof EntrepreneursRoute
  JoinRoute: typeof JoinRoute
  JuniorRoute: typeof JuniorRoute
  ProgramsRoute: typeof ProgramsRoute
  YoungRoute: typeof YoungRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrepreneurs': {
      id: '/entrepreneurs'
      path: '/entrepreneurs'
      fullPath: '/entrepreneurs'
      preLoaderRoute: typeof EntrepreneursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/junior': {
      id: '/junior'
      path: '/junior'
      fullPath: '/junior'
      preLoaderRoute: typeof JuniorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/young': {
      id: '/young'
      path: '/young'
      fullPath: '/young'
      preLoaderRoute: typeof YoungRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ClassesRoute: ClassesRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EntrepreneursRoute: EntrepreneursRoute,
  JoinRoute: JoinRoute,
  JuniorRoute: JuniorRoute,
  ProgramsRoute: ProgramsRoute,
  YoungRoute: YoungRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
